spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5435/payments
    username: fulfillx
    password: fulfillx
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.block.ms: 2000
        request.timeout.ms: 2000
        delivery.timeout.ms: 5000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082