spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: fulfillx
    password: fulfillx
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 2000
        request.timeout.ms: 2000
        delivery.timeout.ms: 5000
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false