spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: fulfillx
    password: fulfillx
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false